### ISSUE TITLE
pnpm dev fail, cause: No matching export in "browser-external:url" for import "fileURLToPath"

### ISSUE THREAD

**Issue by r0bin-zheng** [importantimport/gumori-you#1]
use node.js 14.20.0 

````
unocss v0.44.7                                                                                                                                                                                         21:43:37
start UnoCSS in watch mode...                                                                                                                                                                          21:43:37
i Watching for changes in src/**/*.astro                                                                                                                                                               21:43:38
   astro  v1.0.0-beta.73 started in 36ms

  ┃ Local    http://localhost:3000/
  ┃ Network  use --host to expose

  ▶ This is a  beta  prerelease build
    Feedback? https://astro.build/issues

✘ [ERROR] No matching export in "browser-external:url" for import "fileURLToPath"

    node_modules/.pnpm/rehype-pretty-code@0.3.2_shiki@0.10.1/node_modules/rehype-pretty-code/dist/rehype-pretty-code.js:4:9:
      4 │ import { fileURLToPath } from 'url';
        ╵          ~~~~~~~~~~~~~

21:43:42 [vite] error while updating dependencies:
Error: Build failed with 1 error:
node_modules/.pnpm/rehype-pretty-code@0.3.2_shiki@0.10.1/node_modules/rehype-pretty-code/dist/rehype-pretty-code.js:4:9: ERROR: No matching export in "browser-external:url" for import "fileURLToPath"
    at failureErrorWithLog (D:\Projects\gumori-you\gumori-you\node_modules\.pnpm\esbuild@0.14.50\node_modules\esbuild\lib\main.js:1615:15)
    at D:\Projects\gumori-you\gumori-you\node_modules\.pnpm\esbuild@0.14.50\node_modules\esbuild\lib\main.js:1257:28
    at runOnEndCallbacks (D:\Projects\gumori-you\gumori-you\node_modules\.pnpm\esbuild@0.14.50\node_modules\esbuild\lib\main.js:1037:63)
    at buildResponseToResult (D:\Projects\gumori-you\gumori-you\node_modules\.pnpm\esbuild@0.14.50\node_modules\esbuild\lib\main.js:1255:7)
    at D:\Projects\gumori-you\gumori-you\node_modules\.pnpm\esbuild@0.14.50\node_modules\esbuild\lib\main.js:1368:14
    at D:\Projects\gumori-you\gumori-you\node_modules\.pnpm\esbuild@0.14.50\node_modules\esbuild\lib\main.js:669:9
    at handleIncomingPacket (D:\Projects\gumori-you\gumori-you\node_modules\.pnpm\esbuild@0.14.50\node_modules\esbuild\lib\main.js:766:9)
    at Socket.readFromStdout (D:\Projects\gumori-you\gumori-you\node_modules\.pnpm\esbuild@0.14.50\node_modules\esbuild\lib\main.js:635:7)
    at Socket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:293:12)
````

**Comment by kwaa** [comment]
I don't know how to fix this,
but development and builds should be unaffected for now.
(maybe just waiting for dependency updates?)
also, if have a solution, pls feel free to reply or submit a PR :)

**Comment by kwaa** [comment]
After testing, filling `['url']` into `vite.optimizeDeps.exclude` seems to work.

```ts
vite: {
  optimizeDeps: { exclude: ['url'] },
  ...
}
```
